-- local rt = require("rust-tools");
--
-- rt.setup({
--   inlay_hints = {
--     auto = true,
--     only_current_line = false,
--     show_parameter_hints = true,
--   }
-- })
--
-- rt.inlay_hints.set()
-- rt.inlay_hints.enable()

